In [1]:
import pandas as pd 
import wandb
import numpy as np
api = wandb.Api()

In [2]:
metrics = ['test/result_acc/eval/'+ x for x in ['I', 'SS', 'LS', 'SL', 'LL']] + ['test/result_acc/avg']

In [3]:
def latex(means, stds, transpose=False, prefix='', suffix=''):
    means = np.array(means)
    stds = np.array(stds)
    if transpose:
        means = np.transpose(means)
        stds = np.transpose(stds)
    for i in range(means.shape[0]):
        print(prefix, end='')
        for j in range(means.shape[1]):
            m = means[i,j]
            s = stds[i,j]
            print(f'{m:.1f}$\\pm${s:.1f}', end=' ')
        print(suffix)

# Symbol inputs

In [5]:
runs = api.runs("qli/HINT_main_res_symbol")
summary_list = [] 
for run in runs: 
    # .summary contains the output keys/values for metrics like accuracy.
    #  We call ._json_dict to omit large files 
    summary = {'name': run.name}
    summary.update(run.summary._json_dict)
    summary.update(run.config)
    summary_list.append(summary)
df = {k: [x.get(k, None) for x in summary_list] for k in summary_list[0]}
df = pd.DataFrame(df)

In [9]:
means = df.groupby('model')[metrics].median() * 100
stds = df.groupby('model')[metrics].std() * 100
display(means)
display(stds)
latex(means, stds, False)

,test/result_acc/eval/I,test/result_acc/eval/SS,test/result_acc/eval/LS,test/result_acc/eval/SL,test/result_acc/eval/LL,test/result_acc/avg
model,,,,,,
GRU,74.879760,68.1250,42.10,10.462963,14.03,41.340626
GRU_attn,76.242485,69.5375,42.78,10.451389,15.06,42.509653
LSTM,84.338677,79.6250,63.67,11.724537,22.08,52.284427
LSTM_attn,92.875752,90.8625,74.89,12.118056,24.26,58.882454
TRAN.opennmt,93.927856,91.0500,33.24,11.504630,11.51,47.423852
TRAN.relative,96.633267,95.1000,72.10,11.759259,22.31,59.367224
TRAN.relative_universal,97.995992,96.7750,78.24,11.666667,22.42,61.516517

,test/result_acc/eval/I,test/result_acc/eval/SS,test/result_acc/eval/LS,test/result_acc/eval/SL,test/result_acc/eval/LL,test/result_acc/avg
model,,,,,,
GRU,1.616668,0.476757,1.868007,0.162738,0.754500,0.599847
GRU_attn,0.635479,0.595333,1.475490,0.221637,1.187948,0.696203
LSTM,5.249903,5.963283,6.112027,0.259915,1.380895,3.789308
LSTM_attn,1.372464,1.066002,1.477099,0.158907,0.295719,0.736074
TRAN.opennmt,0.342914,0.529519,1.229606,0.131609,0.740223,0.428692
TRAN.relative,0.279539,0.359839,1.487622,0.151439,0.556309,0.518608
TRAN.relative_universal,0.341785,0.581458,2.857539,0.265650,1.094153,0.912073

74.9$\pm$1.6 68.1$\pm$0.5 42.1$\pm$1.9 10.5$\pm$0.2 14.0$\pm$0.8 41.3$\pm$0.6
76.2$\pm$0.6 69.5$\pm$0.6 42.8$\pm$1.5 10.5$\pm$0.2 15.1$\pm$1.2 42.5$\pm$0.7
84.3$\pm$5.2 79.6$\pm$6.0 63.7$\pm$6.1 11.7$\pm$0.3 22.1$\pm$1.4 52.3$\pm$3.8
92.9$\pm$1.4 90.9$\pm$1.1 74.9$\pm$1.5 12.1$\pm$0.2 24.3$\pm$0.3 58.9$\pm$0.7
93.9$\pm$0.3 91.0$\pm$0.5 33.2$\pm$1.2 11.5$\pm$0.1 11.5$\pm$0.7 47.4$\pm$0.4
96.6$\pm$0.3 95.1$\pm$0.4 72.1$\pm$1.5 11.8$\pm$0.2 22.3$\pm$0.6 59.4$\pm$0.5
98.0$\pm$0.3 96.8$\pm$0.6 78.2$\pm$2.9 11.7$\pm$0.3 22.4$\pm$1.1 61.5$\pm$0.9

# Image inputs

In [10]:
def filter_run(summary):
    return 'train_size' not in summary or summary['train_size'] is None

runs = api.runs("qli/HINT_image")
summary_list = [] 
for run in runs: 
    # .summary contains the output keys/values for metrics like accuracy.
    #  We call ._json_dict to omit large files 
    summary = {'name': run.name}
    summary.update(run.summary._json_dict)
    summary.update(run.config)
    if filter_run(summary):
        summary_list.append(summary)
df = {k: [x.get(k, '') for x in summary_list] for k in summary_list[0]}
df = pd.DataFrame(df)
print('number of runs:', len(summary_list))

number of runs: 35

In [12]:
means = df.groupby('model')[metrics].median() * 100
stds = df.groupby('model')[metrics].std() * 100
display(means)
display(stds)
latex(means, stds, False)

,test/result_acc/eval/I,test/result_acc/eval/SS,test/result_acc/eval/LS,test/result_acc/eval/SL,test/result_acc/eval/LL,test/result_acc/avg
model,,,,,,
GRU,61.292585,53.3500,30.54,9.166667,11.89,33.200343
GRU_attn,66.683367,58.6875,33.11,9.409722,12.78,35.900901
LSTM,80.030060,76.2000,55.71,10.914352,19.79,48.580009
LSTM_attn,83.897796,79.7375,62.03,11.250000,20.99,51.454311
TRAN.opennmt,20.931864,9.3000,5.71,1.469907,2.87,8.258258
TRAN.relative,86.182365,83.0625,60.08,10.868056,19.38,51.720292
TRAN.relative_universal,88.416834,85.9500,62.52,10.902778,19.00,53.146718

,test/result_acc/eval/I,test/result_acc/eval/SS,test/result_acc/eval/LS,test/result_acc/eval/SL,test/result_acc/eval/LL,test/result_acc/avg
model,,,,,,
GRU,1.395270,1.708010,1.170333,0.219145,0.535658,0.884377
GRU_attn,2.035223,2.151337,2.678221,0.314785,0.993318,1.599756
LSTM,5.680000,7.378670,8.220324,0.641782,2.600052,4.905259
LSTM_attn,0.863022,0.788323,2.481618,0.075631,0.812361,0.975326
TRAN.opennmt,0.391077,0.227829,0.261017,0.340758,0.548753,0.255478
TRAN.relative,0.892470,1.279282,2.296319,0.203519,0.487155,0.990676
TRAN.relative_universal,1.272454,1.309479,4.056251,0.232117,1.044332,1.579056

61.3$\pm$1.4 53.3$\pm$1.7 30.5$\pm$1.2 9.2$\pm$0.2 11.9$\pm$0.5 33.2$\pm$0.9
66.7$\pm$2.0 58.7$\pm$2.2 33.1$\pm$2.7 9.4$\pm$0.3 12.8$\pm$1.0 35.9$\pm$1.6
80.0$\pm$5.7 76.2$\pm$7.4 55.7$\pm$8.2 10.9$\pm$0.6 19.8$\pm$2.6 48.6$\pm$4.9
83.9$\pm$0.9 79.7$\pm$0.8 62.0$\pm$2.5 11.2$\pm$0.1 21.0$\pm$0.8 51.5$\pm$1.0
20.9$\pm$0.4 9.3$\pm$0.2 5.7$\pm$0.3 1.5$\pm$0.3 2.9$\pm$0.5 8.3$\pm$0.3
86.2$\pm$0.9 83.1$\pm$1.3 60.1$\pm$2.3 10.9$\pm$0.2 19.4$\pm$0.5 51.7$\pm$1.0
88.4$\pm$1.3 86.0$\pm$1.3 62.5$\pm$4.1 10.9$\pm$0.2 19.0$\pm$1.0 53.1$\pm$1.6